name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run Linter
      run: npm run lint
      
    - name: Run Unit Tests
      run: npm run test
      
    - name: Build Extension
      run: npm run build
      
    - name: Archive production artifacts
      uses: actions/upload-artifact@v4
      with:
        name: extension-build
        path: dist/
